input {
  tcp {
    port => 5000
  }
}

filter {
  grok {
    match => {
      "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} sshd.*Failed password for %{USERNAME:user} from %{IP:src_ip}"
    }
  }

  mutate {
    add_field => {
      "pipeline" => "mini-siem"
      "event_type" => "authentication_failure"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "siem-auth-%{+YYYY.MM.dd}"
  }

  kafka {
    bootstrap_servers => "kafka:9092"
    topic_id => "siem-events"
    codec => json
  }

  stdout {
    codec => rubydebug
  }
}
