-- SOAR V3：租户隔离、版本发布治理、父子流程和分布式 Connector 保护状态。
CREATE TABLE tenants (
    id          VARCHAR(64) PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    status      VARCHAR(16) NOT NULL DEFAULT 'active',
    created_by  VARCHAR(128) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tenants_status_ck CHECK (status IN ('active', 'disabled'))
);

INSERT INTO tenants(id, name, created_by) VALUES ('default', '默认租户', 'migration');

CREATE TABLE tenant_memberships (
    tenant_id   VARCHAR(64) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    username    VARCHAR(128) NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    tenant_role VARCHAR(32) NOT NULL DEFAULT 'member',
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, username),
    CONSTRAINT tenant_membership_role_ck CHECK (tenant_role IN ('owner', 'member', 'viewer'))
);

INSERT INTO tenant_memberships(tenant_id, username, tenant_role)
SELECT 'default', username, CASE WHEN role_name = 'admin' THEN 'owner' ELSE 'member' END FROM users;

ALTER TABLE soar_executions ADD COLUMN tenant_id VARCHAR(64) NOT NULL DEFAULT 'default';
ALTER TABLE soar_executions ADD COLUMN parent_execution_id VARCHAR(128);
ALTER TABLE soar_executions ADD COLUMN parent_node_id VARCHAR(128);
ALTER TABLE soar_executions ADD CONSTRAINT soar_execution_tenant_fk
    FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE soar_executions ADD CONSTRAINT soar_execution_parent_fk
    FOREIGN KEY (parent_execution_id) REFERENCES soar_executions(id) ON DELETE SET NULL;
DROP INDEX soar_execution_dedup_uq;
CREATE UNIQUE INDEX soar_execution_tenant_dedup_uq
    ON soar_executions (tenant_id, dedup_key);
CREATE INDEX soar_execution_tenant_updated_idx
    ON soar_executions (tenant_id, updated_at DESC);
CREATE INDEX soar_execution_parent_idx
    ON soar_executions (parent_execution_id, parent_node_id);

ALTER TABLE soar_step_executions DROP CONSTRAINT soar_step_status_ck;
ALTER TABLE soar_step_executions ADD CONSTRAINT soar_step_status_ck CHECK (status IN
    ('running', 'waiting_approval', 'waiting_child', 'succeeded', 'failed', 'retrying',
     'skipped', 'rejected', 'cancelled'));

CREATE TABLE soar_playbook_revisions (
    tenant_id          VARCHAR(64) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    playbook_id        VARCHAR(128) NOT NULL,
    revision           INTEGER NOT NULL,
    semantic_version   VARCHAR(64) NOT NULL,
    state              VARCHAR(24) NOT NULL,
    definition_json    TEXT NOT NULL,
    layout_json        TEXT NOT NULL DEFAULT '{}',
    rollout_percentage INTEGER NOT NULL DEFAULT 0,
    review_note        TEXT,
    created_by         VARCHAR(128) NOT NULL,
    reviewed_by        VARCHAR(128),
    published_by       VARCHAR(128),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at        TIMESTAMP WITH TIME ZONE,
    published_at       TIMESTAMP WITH TIME ZONE,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lock_version       BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (tenant_id, playbook_id, revision),
    CONSTRAINT soar_playbook_revision_state_ck CHECK (state IN
        ('draft', 'pending_approval', 'approved', 'published', 'rejected', 'retired')),
    CONSTRAINT soar_playbook_rollout_ck CHECK (rollout_percentage BETWEEN 0 AND 100)
);
CREATE INDEX soar_playbook_revision_state_idx
    ON soar_playbook_revisions (tenant_id, state, playbook_id, revision DESC);

CREATE TABLE soar_connector_runtime (
    tenant_id            VARCHAR(64) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    connector_id         VARCHAR(128) NOT NULL,
    window_started_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    window_calls         INTEGER NOT NULL DEFAULT 0,
    daily_bucket         VARCHAR(10) NOT NULL,
    daily_calls          INTEGER NOT NULL DEFAULT 0,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    circuit_open_until   TIMESTAMP WITH TIME ZONE,
    probe_in_flight      BOOLEAN NOT NULL DEFAULT FALSE,
    in_flight            INTEGER NOT NULL DEFAULT 0,
    in_flight_expires_at TIMESTAMP WITH TIME ZONE,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, connector_id)
);

CREATE TABLE soar_connector_invocations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      VARCHAR(64) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    connector_id   VARCHAR(128) NOT NULL,
    operation      VARCHAR(128) NOT NULL,
    execution_id   VARCHAR(128),
    outcome        VARCHAR(24) NOT NULL,
    duration_ms    BIGINT NOT NULL,
    error_code     VARCHAR(64),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX soar_connector_invocation_tenant_idx
    ON soar_connector_invocations (tenant_id, connector_id, created_at DESC);
