-- Managed Detection Runtime: immutable authoring snapshots and desired deployment state.
CREATE TABLE detection_rule (
    rule_key    VARCHAR(128) PRIMARY KEY,
    name        VARCHAR(160) NOT NULL,
    description VARCHAR(2000) NOT NULL DEFAULT '',
    category    VARCHAR(64) NOT NULL,
    owner       VARCHAR(255),
    archived    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rule_revision (
    revision_id    UUID PRIMARY KEY,
    rule_key       VARCHAR(128) NOT NULL REFERENCES detection_rule(rule_key),
    revision       INTEGER NOT NULL,
    definition_json TEXT NOT NULL,
    content_hash   VARCHAR(64) NOT NULL,
    source_commit  VARCHAR(128) NOT NULL,
    created_by     VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rule_revision_version_uq UNIQUE (rule_key, revision),
    CONSTRAINT rule_revision_hash_uq UNIQUE (rule_key, content_hash)
);

CREATE TABLE detection_plan (
    plan_id          UUID PRIMARY KEY,
    revision_id      UUID NOT NULL REFERENCES rule_revision(revision_id),
    compiler_version VARCHAR(64) NOT NULL,
    plan_json        TEXT NOT NULL,
    plan_hash        VARCHAR(64) NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT detection_plan_identity_uq UNIQUE (revision_id, compiler_version, plan_hash)
);

CREATE TABLE rule_deployment (
    deployment_id       UUID PRIMARY KEY,
    tenant_id           VARCHAR(255) NOT NULL,
    rule_key            VARCHAR(128) NOT NULL REFERENCES detection_rule(rule_key),
    desired_revision_id UUID NOT NULL REFERENCES rule_revision(revision_id),
    desired_state       VARCHAR(32) NOT NULL,
    generation          BIGINT NOT NULL DEFAULT 1,
    observed_generation BIGINT NOT NULL DEFAULT 0,
    target_cluster      VARCHAR(255) NOT NULL DEFAULT 'default',
    status              VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    last_error          VARCHAR(2000),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rule_deployment_scope_uq UNIQUE (tenant_id, rule_key),
    CONSTRAINT rule_deployment_state_ck CHECK (desired_state IN ('RUNNING', 'STOPPED'))
);

CREATE TABLE rule_deployment_history (
    history_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deployment_id       UUID NOT NULL REFERENCES rule_deployment(deployment_id),
    tenant_id           VARCHAR(255) NOT NULL,
    rule_key            VARCHAR(128) NOT NULL,
    desired_revision_id UUID NOT NULL,
    desired_state       VARCHAR(32) NOT NULL,
    generation          BIGINT NOT NULL,
    status              VARCHAR(32) NOT NULL,
    actor               VARCHAR(255) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX rule_revision_rule_key_idx ON rule_revision(rule_key, revision DESC);
CREATE INDEX detection_plan_revision_idx ON detection_plan(revision_id);
CREATE INDEX rule_deployment_tenant_idx ON rule_deployment(tenant_id);
CREATE INDEX rule_deployment_history_scope_idx
    ON rule_deployment_history(tenant_id, rule_key, created_at DESC);
