-- Observed-state foundation for managed detection jobs.  The physical controller is a later phase.

CREATE TABLE detection_job_group (
    tenant_id              VARCHAR(64)  NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    group_key              VARCHAR(512) NOT NULL,
    target_cluster         VARCHAR(255) NOT NULL,
    source_family          VARCHAR(255) NOT NULL DEFAULT 'siem-events',
    category               VARCHAR(64)  NOT NULL,
    bucket                 INTEGER      NOT NULL,
    desired_generation     BIGINT       NOT NULL DEFAULT 1,
    expected_manifest_json TEXT         NOT NULL,
    expected_manifest_hash VARCHAR(128) NOT NULL,
    status                 VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    job_id                 VARCHAR(255),
    job_key                VARCHAR(255),
    last_error             VARCHAR(2000),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, group_key),
    CONSTRAINT detection_job_group_generation_ck CHECK (desired_generation >= 0),
    CONSTRAINT detection_job_group_bucket_ck CHECK (bucket >= 0),
    CONSTRAINT detection_job_group_status_ck CHECK (status IN
        ('PENDING', 'DEPLOYING', 'RUNNING', 'DEGRADED', 'OUT_OF_SYNC',
         'FAILED', 'DISABLED', 'UNKNOWN'))
);

CREATE TABLE rule_job_assignment (
    tenant_id       VARCHAR(64)  NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    rule_key        VARCHAR(128) NOT NULL REFERENCES detection_rule(rule_key) ON DELETE CASCADE,
    deployment_id   UUID         NOT NULL REFERENCES rule_deployment(deployment_id) ON DELETE CASCADE,
    revision        BIGINT       NOT NULL,
    plan_id         UUID         NOT NULL REFERENCES detection_plan(plan_id),
    plan_hash       VARCHAR(128) NOT NULL,
    group_key       VARCHAR(512) NOT NULL,
    generation      BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, rule_key),
    CONSTRAINT rule_job_assignment_generation_ck CHECK (generation >= 0),
    CONSTRAINT rule_job_assignment_group_fk FOREIGN KEY (tenant_id, group_key)
        REFERENCES detection_job_group(tenant_id, group_key) ON DELETE CASCADE
);

-- Append-only observations.  The newest row for a scope is the current observation;
-- retaining all rows makes controller/audit replay possible.
CREATE TABLE detection_runtime_manifest (
    manifest_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR(64)  NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    group_key       VARCHAR(512) NOT NULL,
    target_cluster  VARCHAR(255) NOT NULL,
    job_id          VARCHAR(255),
    job_key         VARCHAR(255),
    generation      BIGINT       NOT NULL,
    manifest_json   TEXT         NOT NULL,
    manifest_hash   VARCHAR(128) NOT NULL,
    observed_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT detection_runtime_manifest_generation_ck CHECK (generation >= 0)
);

CREATE TABLE rule_runtime_status (
    tenant_id          VARCHAR(64)  NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    rule_key           VARCHAR(128) NOT NULL REFERENCES detection_rule(rule_key) ON DELETE CASCADE,
    deployment_id      UUID REFERENCES rule_deployment(deployment_id) ON DELETE SET NULL,
    group_key          VARCHAR(512),
    target_cluster     VARCHAR(255),
    job_id             VARCHAR(255),
    job_key            VARCHAR(255),
    observed_revision  BIGINT,
    observed_generation BIGINT,
    observed_plan_hash VARCHAR(128),
    runtime_state      VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    last_seen          TIMESTAMP WITH TIME ZONE,
    last_event         TIMESTAMP WITH TIME ZONE,
    last_match         TIMESTAMP WITH TIME ZONE,
    last_alert         TIMESTAMP WITH TIME ZONE,
    last_seen_at       TIMESTAMP WITH TIME ZONE,
    last_event_at      TIMESTAMP WITH TIME ZONE,
    last_match_at      TIMESTAMP WITH TIME ZONE,
    last_alert_at      TIMESTAMP WITH TIME ZONE,
    error_code         VARCHAR(128),
    error_message      VARCHAR(2000),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, rule_key),
    CONSTRAINT rule_runtime_status_generation_ck CHECK
        (observed_generation IS NULL OR observed_generation >= 0),
    CONSTRAINT rule_runtime_status_state_ck CHECK (runtime_state IN
        ('PENDING', 'DEPLOYING', 'RUNNING', 'DEGRADED', 'OUT_OF_SYNC',
         'FAILED', 'DISABLED', 'UNKNOWN'))
);

CREATE INDEX detection_job_group_tenant_cluster_idx
    ON detection_job_group(tenant_id, target_cluster, status, updated_at DESC);
CREATE INDEX rule_job_assignment_group_idx
    ON rule_job_assignment(tenant_id, group_key, rule_key);
CREATE INDEX detection_runtime_manifest_scope_idx
    ON detection_runtime_manifest(tenant_id, group_key, target_cluster, observed_at DESC);
CREATE INDEX rule_runtime_status_scope_idx
    ON rule_runtime_status(tenant_id, group_key, target_cluster, runtime_state);
CREATE INDEX rule_runtime_status_updated_idx
    ON rule_runtime_status(tenant_id, updated_at DESC);
