-- 控制面初始模型。事件、告警和实体风险仍保留在 Elasticsearch。

CREATE TABLE roles (
    name             VARCHAR(32) PRIMARY KEY,
    description      VARCHAR(255) NOT NULL,
    permissions_json TEXT NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (name, description, permissions_json) VALUES
    ('admin', '系统管理员', '["all"]'),
    ('analyst', '告警分析师', '["alerts:read","alerts:write"]'),
    ('ops', '运维人员', '["sources:write","health:read"]'),
    ('audit', '审计只读', '["read"]');

CREATE TABLE users (
    id            VARCHAR(128) PRIMARY KEY,
    username      VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_name     VARCHAR(32) NOT NULL REFERENCES roles(name),
    status        VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_status_ck CHECK (status IN ('active', 'disabled'))
);

CREATE TABLE audit_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor      VARCHAR(128) NOT NULL,
    action     VARCHAR(128) NOT NULL,
    target     VARCHAR(512),
    metadata_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX audit_logs_created_at_idx ON audit_logs (created_at DESC);

CREATE TABLE cases (
    id              VARCHAR(128) PRIMARY KEY,
    title           VARCHAR(512) NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'open',
    aggregation     VARCHAR(32) NOT NULL DEFAULT 'manual',
    operator        VARCHAR(128) NOT NULL,
    verdict         VARCHAR(32),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at       TIMESTAMP WITH TIME ZONE,
    alert_ids_json  TEXT NOT NULL DEFAULT '[]',
    entities_json   TEXT NOT NULL DEFAULT '[]',
    version         BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT cases_status_ck CHECK (status IN ('open', 'investigating', 'resolved')),
    CONSTRAINT cases_verdict_ck CHECK (verdict IS NULL OR verdict IN ('true_positive', 'false_positive', 'duplicate'))
);
CREATE INDEX cases_status_updated_at_idx ON cases (status, updated_at DESC);

CREATE TABLE case_alerts (
    case_id    VARCHAR(128) NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    alert_id   VARCHAR(256) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (case_id, alert_id),
    CONSTRAINT case_alerts_alert_unique UNIQUE (alert_id)
);
CREATE INDEX case_alerts_alert_id_idx ON case_alerts (alert_id);

CREATE TABLE notifications (
    id          VARCHAR(128) PRIMARY KEY,
    type        VARCHAR(128) NOT NULL,
    target      VARCHAR(512) NOT NULL,
    message     TEXT NOT NULL,
    is_read     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX notifications_unread_idx ON notifications (is_read, created_at DESC);
CREATE INDEX notifications_frequency_idx ON notifications (type, target, created_at DESC);

CREATE TABLE background_tasks (
    id          VARCHAR(128) PRIMARY KEY,
    task_type   VARCHAR(128) NOT NULL,
    resource_id VARCHAR(256),
    status      VARCHAR(32) NOT NULL,
    progress    INTEGER NOT NULL DEFAULT 0,
    message     TEXT,
    error       TEXT,
    started_at  TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT background_tasks_status_ck CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled'))
);
CREATE INDEX background_tasks_updated_at_idx ON background_tasks (updated_at DESC);
