-- 可靠性边界：案件 ES 镜像通过 outbox 收敛，后台任务通过数据库租约避免重复执行。
CREATE TABLE case_mirror_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id         VARCHAR(128) NOT NULL,
    operation       VARCHAR(16) NOT NULL,
    payload_json    TEXT,
    status          VARCHAR(16) NOT NULL DEFAULT 'pending',
    attempts        INTEGER NOT NULL DEFAULT 0,
    available_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_until    TIMESTAMP WITH TIME ZONE,
    lease_owner     VARCHAR(128),
    last_error      TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT case_mirror_outbox_operation_ck CHECK (operation IN ('upsert', 'delete')),
    CONSTRAINT case_mirror_outbox_status_ck CHECK (status IN ('pending', 'in_flight', 'succeeded', 'failed'))
);
CREATE INDEX case_mirror_outbox_ready_idx
    ON case_mirror_outbox (status, available_at, locked_until);

ALTER TABLE background_tasks ADD COLUMN lease_owner VARCHAR(128);
ALTER TABLE background_tasks ADD COLUMN lease_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE background_tasks ADD COLUMN heartbeat_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE background_tasks ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE background_tasks ADD COLUMN max_attempts INTEGER NOT NULL DEFAULT 3;
