-- SOAR V2：持久化 Worker 租约、图 frontier、自动触发去重和执行时间线。
ALTER TABLE soar_executions ADD COLUMN current_node VARCHAR(128);
ALTER TABLE soar_executions ADD COLUMN frontier_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE soar_executions ADD COLUMN trigger_type VARCHAR(32) NOT NULL DEFAULT 'manual';
ALTER TABLE soar_executions ADD COLUMN dedup_key VARCHAR(512);
ALTER TABLE soar_executions ADD COLUMN next_run_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE soar_executions ADD COLUMN lease_owner VARCHAR(128);
ALTER TABLE soar_executions ADD COLUMN lease_expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE soar_executions ADD COLUMN cancel_requested BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE soar_executions ADD COLUMN pause_requested BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE soar_executions ADD COLUMN nodes_executed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE soar_executions DROP CONSTRAINT soar_execution_status_ck;
ALTER TABLE soar_executions ADD CONSTRAINT soar_execution_status_ck CHECK (status IN
    ('queued', 'running', 'waiting_approval', 'paused', 'succeeded', 'failed', 'rejected', 'cancelled'));
CREATE UNIQUE INDEX soar_execution_dedup_uq ON soar_executions (dedup_key);
CREATE INDEX soar_execution_worker_idx ON soar_executions (status, next_run_at, lease_expires_at);

ALTER TABLE soar_step_executions ADD COLUMN node_type VARCHAR(32) NOT NULL DEFAULT 'action';
ALTER TABLE soar_step_executions ADD COLUMN attempt INTEGER NOT NULL DEFAULT 1;
ALTER TABLE soar_step_executions ADD COLUMN max_attempts INTEGER NOT NULL DEFAULT 1;
ALTER TABLE soar_step_executions ADD COLUMN scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE soar_step_executions ADD COLUMN duration_ms BIGINT;
ALTER TABLE soar_step_executions DROP CONSTRAINT soar_step_status_ck;
ALTER TABLE soar_step_executions ADD CONSTRAINT soar_step_status_ck CHECK (status IN
    ('running', 'waiting_approval', 'succeeded', 'failed', 'retrying', 'skipped', 'rejected', 'cancelled'));

CREATE TABLE soar_execution_events (
    sequence       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id  VARCHAR(128) NOT NULL REFERENCES soar_executions(id) ON DELETE CASCADE,
    event_type    VARCHAR(64) NOT NULL,
    node_id       VARCHAR(128),
    actor         VARCHAR(128) NOT NULL,
    details_json  TEXT NOT NULL DEFAULT '{}',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX soar_execution_events_idx ON soar_execution_events (execution_id, sequence);
